import React, { useState } from 'react';
import { Upload, Camera, FileImage, Eye, Trash2, Download, CheckCircle, AlertCircle, Loader } from 'lucide-react';
import { OCRService, GoogleDriveService, RoomRateCalculator } from '../services/integrationServices';

const SlipManager = () => {
  const [slips, setSlips] = useState([]);
  const [uploading, setUploading] = useState(false);
  const [processing, setProcessing] = useState(false);
  const [selectedSlip, setSelectedSlip] = useState(null);

  // Initialize services with API key
  const ocrService = new OCRService(process.env.REACT_APP_GOOGLE_API_KEY);
  const roomCalculator = new RoomRateCalculator();

  // OCR Processing Function
  const processOCR = async (imageFile) => {
    setProcessing(true);
    
    try {
      // Use real OCR service if API key is available
      if (process.env.REACT_APP_GOOGLE_API_KEY) {
        const ocrData = await ocrService.processImage(imageFile);
        setProcessing(false);
        return ocrData;
      } else {
        // Fallback to mock data
        await new Promise(resolve => setTimeout(resolve, 2000));
        const mockData = {
          amount: Math.floor(Math.random() * 10000) + 1000,
          date: new Date().toISOString().split('T')[0],
          time: new Date().toLocaleTimeString('th-TH'),
          bankAccount: '1234567890',
          reference: 'REF' + Math.random().toString(36).substr(2, 9).toUpperCase(),
          transferType: 'โอนเงิน',
          confidence: 0.95
        };
        setProcessing(false);
        return mockData;
      }
    } catch (error) {
      console.error('OCR processing error:', error);
      setProcessing(false);
      // Return mock data on error
      return {
        amount: 0,
        date: new Date().toISOString().split('T')[0],
        time: new Date().toLocaleTimeString('th-TH'),
        bankAccount: 'N/A',
        reference: 'ERROR',
        transferType: 'ไม่ระบุ',
        confidence: 0.1
      };
    }
  };

  // Upload and Process Slip
  const handleSlipUpload = async (event) => {
    const files = Array.from(event.target.files);
    setUploading(true);

    for (const file of files) {
      try {
        // Create preview URL
        const previewUrl = URL.createObjectURL(file);
        
        // Process OCR
        const ocrData = await processOCR(file);
        
        // Create folder path based on date
        const folderPath = `Slips/${ocrData.date.replace(/-/g, '/')}`;
        
        // Create slip record
        const newSlip = {
          id: Date.now() + Math.random(),
          fileName: file.name,
          fileSize: file.size,
          previewUrl,
          uploadDate: new Date().toISOString(),
          folderPath,
          ocrData,
          status: 'processed',
          verified: false,
          linkedTransaction: null
        };

        setSlips(prev => [...prev, newSlip]);
        
        // Auto-create transaction if confidence is high
        if (ocrData.confidence > 0.9) {
          await createAutoTransaction(newSlip);
        }
        
      } catch (error) {
        console.error('Error processing slip:', error);
      }
    }
    
    setUploading(false);
  };

  // Auto-create transaction from OCR data
  const createAutoTransaction = async (slip) => {
    const transaction = {
      id: Date.now(),
      type: 'รายรับ',
      category: 'ค่าห้องพัก',
      amount: slip.ocrData.amount,
      description: `การโอนเงิน - ${slip.ocrData.reference}`,
      date: slip.ocrData.date,
      slipId: slip.id,
      autoGenerated: true,
      verified: false
    };

    // Link slip to transaction
    slip.linkedTransaction = transaction.id;
    
    // Save to localStorage (in real app, save to database)
    const existingTransactions = JSON.parse(localStorage.getItem('transactions') || '[]');
    existingTransactions.push(transaction);
    localStorage.setItem('transactions', JSON.stringify(existingTransactions));
    
    alert(`สร้างรายการธุรกรรมอัตโนมัติ: ฿${transaction.amount.toLocaleString()}`);
  };

  // Verify slip data
  const verifySlip = (slipId) => {
    setSlips(prev => prev.map(slip => 
      slip.id === slipId ? { ...slip, verified: true } : slip
    ));
    alert('ยืนยันข้อมูลสลิปสำเร็จ!');
  };

  // Calculate room charges
  const calculateRoomCharges = (roomId, checkInDate, checkOutDate) => {
    if (!roomId || !checkInDate || !checkOutDate) return null;
    
    return roomCalculator.calculateCharges(roomId, checkInDate, checkOutDate);
  };

  // Handle room calculation
  const [roomCalc, setRoomCalc] = useState({
    roomId: '',
    checkInDate: '',
    checkOutDate: '',
    result: null
  });

  const handleRoomCalculation = () => {
    if (roomCalc.roomId && roomCalc.checkInDate && roomCalc.checkOutDate) {
      const result = calculateRoomCharges(roomCalc.roomId, roomCalc.checkInDate, roomCalc.checkOutDate);
      setRoomCalc(prev => ({ ...prev, result }));
    } else {
      alert('กรุณากรอกข้อมูลให้ครบถ้วน');
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row gap-4 justify-between items-start sm:items-center">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">จัดการสลิปและ OCR</h2>
          <p className="text-sm text-gray-500 mt-1">อัปโหลด ประมวลผล และจัดการสลิปการโอนเงิน</p>
        </div>
        <div className="flex items-center gap-3">
          <label className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-700 cursor-pointer transition-colors">
            <Upload size={16} />
            อัปโหลดสลิป
            <input
              type="file"
              multiple
              accept="image/*"
              onChange={handleSlipUpload}
              className="hidden"
            />
          </label>
        </div>
      </div>

      {/* Processing Status */}
      {(uploading || processing) && (
        <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
          <div className="flex items-center gap-3">
            <Loader className="animate-spin text-blue-600" size={20} />
            <div>
              <p className="font-medium text-blue-900">
                {processing ? 'กำลังประมวลผล OCR...' : 'กำลังอัปโหลด...'}
              </p>
              <p className="text-sm text-blue-600">
                {processing ? 'กำลังแยกข้อมูลจากรูปภาพ' : 'กำลังเตรียมไฟล์'}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* OCR Statistics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-blue-50 p-4 rounded-xl border border-blue-200">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-bold text-blue-600 uppercase">สลิปทั้งหมด</p>
              <p className="text-2xl font-black text-blue-600 mt-1">{slips.length}</p>
            </div>
            <FileImage className="text-blue-400" size={24} />
          </div>
        </div>
        
        <div className="bg-green-50 p-4 rounded-xl border border-green-200">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-bold text-green-600 uppercase">ยืนยันแล้ว</p>
              <p className="text-2xl font-black text-green-600 mt-1">
                {slips.filter(s => s.verified).length}
              </p>
            </div>
            <CheckCircle className="text-green-400" size={24} />
          </div>
        </div>
        
        <div className="bg-yellow-50 p-4 rounded-xl border border-yellow-200">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-bold text-yellow-600 uppercase">รอตรวจสอบ</p>
              <p className="text-2xl font-black text-yellow-600 mt-1">
                {slips.filter(s => !s.verified).length}
              </p>
            </div>
            <AlertCircle className="text-yellow-400" size={24} />
          </div>
        </div>
        
        <div className="bg-purple-50 p-4 rounded-xl border border-purple-200">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-bold text-purple-600 uppercase">ยอดรวม</p>
              <p className="text-2xl font-black text-purple-600 mt-1">
                ฿{slips.reduce((sum, slip) => sum + (slip.ocrData?.amount || 0), 0).toLocaleString()}
              </p>
            </div>
            <Camera className="text-purple-400" size={24} />
          </div>
        </div>
      </div>

      {/* Slip List */}
      <div className="bg-white rounded-2xl shadow-sm border">
        <div className="p-6 border-b">
          <h3 className="text-lg font-bold">รายการสลิป</h3>
        </div>
        <div className="p-6">
          {slips.length === 0 ? (
            <div className="text-center py-12">
              <FileImage className="mx-auto text-gray-300 mb-4" size={48} />
              <p className="text-gray-500">ยังไม่มีสลิปในระบบ</p>
              <p className="text-sm text-gray-400 mt-1">อัปโหลดสลิปเพื่อเริ่มใช้งาน OCR</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {slips.map((slip) => (
                <div key={slip.id} className="border rounded-xl overflow-hidden hover:shadow-md transition-shadow">
                  {/* Image Preview */}
                  <div className="aspect-video bg-gray-100 relative">
                    <img
                      src={slip.previewUrl}
                      alt={slip.fileName}
                      className="w-full h-full object-cover"
                    />
                    <div className="absolute top-2 right-2">
                      <span className={`px-2 py-1 rounded text-xs font-bold ${
                        slip.verified 
                          ? 'bg-green-100 text-green-800' 
                          : 'bg-yellow-100 text-yellow-800'
                      }`}>
                        {slip.verified ? 'ยืนยันแล้ว' : 'รอตรวจสอบ'}
                      </span>
                    </div>
                  </div>

                  {/* Slip Info */}
                  <div className="p-4">
                    <div className="space-y-2">
                      <div className="flex justify-between items-start">
                        <h4 className="font-medium text-sm truncate">{slip.fileName}</h4>
                        <span className="text-xs text-gray-500">
                          {(slip.fileSize / 1024 / 1024).toFixed(1)} MB
                        </span>
                      </div>
                      
                      {slip.ocrData && (
                        <div className="space-y-1 text-sm">
                          <div className="flex justify-between">
                            <span className="text-gray-600">จำนวนเงิน:</span>
                            <span className="font-bold text-green-600">
                              ฿{slip.ocrData.amount.toLocaleString()}
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">วันที่:</span>
                            <span>{slip.ocrData.date}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">เวลา:</span>
                            <span>{slip.ocrData.time}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">อ้างอิง:</span>
                            <span className="font-mono text-xs">{slip.ocrData.reference}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">ความแม่นยำ:</span>
                            <span className={`font-bold ${
                              slip.ocrData.confidence > 0.9 ? 'text-green-600' : 
                              slip.ocrData.confidence > 0.7 ? 'text-yellow-600' : 'text-red-600'
                            }`}>
                              {(slip.ocrData.confidence * 100).toFixed(1)}%
                            </span>
                          </div>
                        </div>
                      )}
                      
                      <div className="text-xs text-gray-500">
                        <p>โฟลเดอร์: {slip.folderPath}</p>
                        <p>อัปโหลด: {new Date(slip.uploadDate).toLocaleString('th-TH')}</p>
                      </div>
                    </div>

                    {/* Actions */}
                    <div className="flex items-center gap-2 mt-4">
                      <button
                        onClick={() => setSelectedSlip(slip)}
                        className="flex-1 px-3 py-2 text-sm bg-blue-50 text-blue-700 rounded-lg hover:bg-blue-100 transition-colors"
                      >
                        <Eye size={14} className="inline mr-1" />
                        ดูรายละเอียด
                      </button>
                      
                      {!slip.verified && (
                        <button
                          onClick={() => verifySlip(slip.id)}
                          className="px-3 py-2 text-sm bg-green-50 text-green-700 rounded-lg hover:bg-green-100 transition-colors"
                        >
                          <CheckCircle size={14} className="inline mr-1" />
                          ยืนยัน
                        </button>
                      )}
                      
                      <button className="px-3 py-2 text-sm bg-red-50 text-red-700 rounded-lg hover:bg-red-100 transition-colors">
                        <Trash2 size={14} />
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Room Charge Calculator */}
      <div className="bg-white rounded-2xl shadow-sm border">
        <div className="p-6 border-b">
          <h3 className="text-lg font-bold">คำนวณค่าห้องพัก</h3>
        </div>
        <div className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                หมายเลขห้อง
              </label>
              <select 
                value={roomCalc.roomId}
                onChange={(e) => setRoomCalc(prev => ({ ...prev, roomId: e.target.value }))}
                className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
              >
                <option value="">เลือกห้อง</option>
                <option value="101">101 - Standard (฿1,500)</option>
                <option value="102">102 - Standard (฿1,500)</option>
                <option value="103">103 - Standard (฿1,500)</option>
                <option value="201">201 - Deluxe (฿2,000)</option>
                <option value="202">202 - Deluxe (฿2,000)</option>
                <option value="203">203 - Deluxe (฿2,000)</option>
                <option value="301">301 - Suite (฿2,500)</option>
                <option value="302">302 - Suite (฿2,500)</option>
                <option value="303">303 - Suite (฿2,500)</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                วันที่เช็คอิน
              </label>
              <input
                type="date"
                value={roomCalc.checkInDate}
                onChange={(e) => setRoomCalc(prev => ({ ...prev, checkInDate: e.target.value }))}
                className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                วันที่เช็คเอาท์
              </label>
              <input
                type="date"
                value={roomCalc.checkOutDate}
                onChange={(e) => setRoomCalc(prev => ({ ...prev, checkOutDate: e.target.value }))}
                className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
              />
            </div>
            <div className="flex items-end">
              <button 
                onClick={handleRoomCalculation}
                className="w-full px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium"
              >
                คำนวณ
              </button>
            </div>
          </div>
          
          {/* Calculation Result */}
          <div className="mt-6 p-4 bg-gray-50 rounded-lg">
            <h4 className="font-medium mb-3">ผลการคำนวณ</h4>
            {roomCalc.result ? (
              <div className="space-y-3">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                  <div>
                    <span className="text-gray-600">ห้อง:</span>
                    <p className="font-bold">{roomCalc.result.roomId}</p>
                  </div>
                  <div>
                    <span className="text-gray-600">ราคา/คืน:</span>
                    <p className="font-bold">฿{roomCalc.result.baseRate.toLocaleString()}</p>
                  </div>
                  <div>
                    <span className="text-gray-600">จำนวนคืน:</span>
                    <p className="font-bold">{roomCalc.result.nights} คืน</p>
                  </div>
                  <div>
                    <span className="text-gray-600">ค่าห้อง:</span>
                    <p className="font-bold">฿{roomCalc.result.roomCharges.toLocaleString()}</p>
                  </div>
                </div>
                
                <div className="border-t pt-3">
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                    <div>
                      <span className="text-gray-600">ยอดรวม:</span>
                      <p className="font-bold">฿{roomCalc.result.subtotal.toLocaleString()}</p>
                    </div>
                    <div>
                      <span className="text-gray-600">ค่าบริการ (10%):</span>
                      <p className="font-bold">฿{roomCalc.result.serviceCharge.toLocaleString()}</p>
                    </div>
                    <div>
                      <span className="text-gray-600">ภาษี (7%):</span>
                      <p className="font-bold">฿{roomCalc.result.taxAmount.toLocaleString()}</p>
                    </div>
                    <div>
                      <span className="text-gray-600">รวมสุทธิ:</span>
                      <p className="font-bold text-green-600 text-lg">฿{roomCalc.result.total.toLocaleString()}</p>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm text-gray-500">
                <div>
                  <span>ห้อง:</span>
                  <p>-</p>
                </div>
                <div>
                  <span>ราคา/คืน:</span>
                  <p>-</p>
                </div>
                <div>
                  <span>จำนวนคืน:</span>
                  <p>-</p>
                </div>
                <div>
                  <span>รวมสุทธิ:</span>
                  <p>-</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Slip Detail Modal */}
      {selectedSlip && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-black/50" onClick={() => setSelectedSlip(null)} />
          <div className="relative bg-white w-full max-w-4xl rounded-2xl overflow-hidden">
            <div className="p-6 border-b">
              <h3 className="text-xl font-bold">รายละเอียดสลิป</h3>
            </div>
            <div className="p-6 max-h-96 overflow-y-auto">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <img
                    src={selectedSlip.previewUrl}
                    alt={selectedSlip.fileName}
                    className="w-full rounded-lg border"
                  />
                </div>
                <div className="space-y-4">
                  <div>
                    <h4 className="font-medium mb-2">ข้อมูล OCR</h4>
                    <div className="space-y-2 text-sm">
                      <div className="flex justify-between">
                        <span>จำนวนเงิน:</span>
                        <span className="font-bold">฿{selectedSlip.ocrData?.amount.toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between">
                        <span>วันที่:</span>
                        <span>{selectedSlip.ocrData?.date}</span>
                      </div>
                      <div className="flex justify-between">
                        <span>เวลา:</span>
                        <span>{selectedSlip.ocrData?.time}</span>
                      </div>
                      <div className="flex justify-between">
                        <span>หมายเลขอ้างอิง:</span>
                        <span className="font-mono">{selectedSlip.ocrData?.reference}</span>
                      </div>
                      <div className="flex justify-between">
                        <span>บัญชีปลายทาง:</span>
                        <span className="font-mono">{selectedSlip.ocrData?.bankAccount}</span>
                      </div>
                    </div>
                  </div>
                  
                  <div>
                    <h4 className="font-medium mb-2">ข้อมูลไฟล์</h4>
                    <div className="space-y-2 text-sm">
                      <div className="flex justify-between">
                        <span>ชื่อไฟล์:</span>
                        <span>{selectedSlip.fileName}</span>
                      </div>
                      <div className="flex justify-between">
                        <span>ขนาดไฟล์:</span>
                        <span>{(selectedSlip.fileSize / 1024 / 1024).toFixed(2)} MB</span>
                      </div>
                      <div className="flex justify-between">
                        <span>โฟลเดอร์:</span>
                        <span>{selectedSlip.folderPath}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="p-6 border-t flex justify-end gap-3">
              <button
                onClick={() => setSelectedSlip(null)}
                className="px-4 py-2 border rounded-lg hover:bg-gray-50"
              >
                ปิด
              </button>
              <button className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
                <Download size={16} className="inline mr-2" />
                ดาวน์โหลด
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default SlipManager;
